const products = [
  {
    id: 1,
    image: "./assets/img/products/product1.webp",
    discount: "-7%",
    name: "Commodo Augue Nisi",
    priceCurrent: 69.00,
    priceOld: 74.00,
  },
  {
    id: 2,
    image: "./assets/img/products/product2.webp",
    discount: "-6%",
    name: "Fringilla Augue",
    priceCurrent: 68.00,
    priceOld: 75.00,
  },
  {
    id: 3,
    image: "./assets/img/products/product3.jpg",
    discount: "-6%",
    name: "Fringilla Augue",
    priceCurrent: 68.00,
    priceOld: 75.00,
  },
  {
    id: 4,
    image: "./assets/img/products/product4.webp",
    discount: "-5%",
    name: "Massa Massa",
    priceCurrent: 75.00,
    priceOld: 80.00,
  },
  {
    id: 5,
    image: "./assets/img/products/product5.webp",
    discount: "-8%",
    name: "Placerat Vestibulum",
    priceCurrent: 65.00,
    priceOld: 70.00,
  },
  {
    id: 6,
    image: "./assets/img/products/product6.webp",
    discount: "-9%",
    name: "Porro Cook",
    priceCurrent: 62.00,
    priceOld: 68.00,
  },
  {
    id: 7,
    image: "./assets/img/products/product7.webp",
    discount: "-4%",
    name: "Sapien Libero",
    priceCurrent: 69.00,
    priceOld: 74.00,
  },
  {
    id: 8,
    image: "./assets/img/products/product8.webp",
    discount: "-6%",
    name: "Vulputate Rutrum",
    priceCurrent: 64.00,
    priceOld: 72.00,
  },
  {
    id: 9,
    image: "./assets/img/products/product9.webp",
    discount: "-8%",
    name: "Adipiscing Cursus",
    priceCurrent: 60.00,
    priceOld: 70.00,
  },
  {
    id: 10,
    image: "./assets/img/products/product10.webp",
    discount: "-9%",
    name: "Donec Eu Cook",
    priceCurrent: 67.00,
    priceOld: 77.00,
  },
];

export default products;